version: '1'
services:
  postgresDB:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: clouddog # init database: cloud_dog
      POSTGRES_PASSWORD: 123456
    restart: always
    ports:
      - 5432:5432
    # # mkdir -p /data/postgres
    volumes:
      - /data/postgres:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      # build static file first
      - /data/node18/dist:/usr/share/nginx/dist
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Hong_Kong
    privileged: true
    depends_on:
      - django

  django:
    container_name: cloud_dog
    image: sunway/clouddog:image20230925
    restart: always
    environment:
      - DJANGO_POSTGRES_DATABASE=clouddog
      - DJANGO_POSTGRES_USER=postgres
      - DJANGO_POSTGRES_PASSWORD=123456
      - DJANGO_POSTGRES_HOST=postgresDB
      - DJANGO_POSTGRES_PORT=5432
      - EMAIL_HOST=123456
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=123456
      - EMAIL_HOST_PASSWORD=123456
    ports:
      - 8000:8000
    depends_on:
      - postgresDB